"""Initial migration.

Revision ID: 925c65fef581
Revises: 
Create Date: 2020-04-18 16:53:34.683519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925c65fef581'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NIM', sa.String(length=10), nullable=True),
    sa.Column('Nama', sa.String(length=20), nullable=True),
    sa.Column('Alamat', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('NIM')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
